# Generated by Django 5.2.1 on 2025-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('country', 'Country'), ('animal', 'Animal'), ('sport', 'Sport'), ('fruit', 'Fruit')], max_length=20)),
            ],
        ),
    ]
