# Generated by Django 5.2.1 on 2025-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('country', 'Country'), ('animal', 'Animal'), ('sport', 'Sport'), ('fruit', 'Fruit'), ('random', 'Random')], max_length=20),
        ),
    ]
